version: "2.2"

services:
  web:
    image: api-resto
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: api-resto
    ports: 
      - 8800:8000
    restart: unless-stopped
       
  cassandra-c01:
    container_name: cassandra-c01
    image: cassandra
    ports:
      - 9047:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=Formation
    volumes:
      - ./data/cassandra-c01:/var/lib/cassandra

  cassandra-c02:
    container_name: cassandra-c02
    image: cassandra
    ports:
      - 9046:9042
    command: /bin/bash -c "sleep 30 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    links:
      - cassandra-c01:seed
    environment:
      - CASSANDRA_SEEDS=seed
      - CASSANDRA_CLUSTER_NAME=Formation
    volumes:
      - ./data/cassandra-c02:/var/lib/cassandra
  